Repository Matrimania/back-end, pull requests merged in 2021-01, with the labels that each got.

#11 Setup
  .travis.yml
  Dockerfile
  app/.flake8
  app/app/__init__.py
  app/app/settings.py
  app/app/urls.py
  app/app/wsgi.py
  app/core/__init__.py
  app/core/admin.py
  app/core/apps.py
  app/core/migrations/0001_initial.py
  app/core/migrations/__init__.py
  app/core/models.py
  app/core/tests/__init__.py
  app/core/tests/test_commands.py
  app/core/tests/test_models.py
  app/manage.py
  docker-compose.yml
  requirements.txt
Labels: Author Resolves Line Comments, BE, Peer Coded, documentation, good first issue

#12 Vendor model
  app/core/migrations/0001_initial.py
  app/core/models.py
  app/core/tests/test_commands.py
  app/core/tests/test_models.py
Labels: BE, Peer Coded, Reviewer Adds Line Comments, Reviewer Resolves Line Comments, Reviewer Thinks Ready To Merge

#15 All weddings api
  app/app/settings.py
  app/app/urls.py
  app/wedding/__init__.py
  app/wedding/apps.py
  app/wedding/serializers.py
  app/wedding/tests/__init__.py
  app/wedding/tests/test_wedding_api.py
  app/wedding/urls.py
  app/wedding/views.py
  requirements.txt
Labels: BE, Peer Coded, Priority #1, Reviewer Adds Line Comments, Reviewer Thinks Ready To Merge

#17 Get guests api
  app/app/urls.py
  app/wedding/serializers.py
  app/wedding/tests/test_guest_api.py
  app/wedding/tests/test_wedding_api.py
  app/wedding/urls.py
  app/wedding/views.py
Labels: Author Adds Line Comments, Author Needs Review, Author Resolves Line Comments, Author Thinks Ready To Merge, BE, Reviewer Adds Line Comments, Reviewer Thinks Ready To Merge

#18 Add Django-cors-headers to settings
  Dockerfile
  app/app/settings.py
  requirements.txt
Labels: Author Thinks Ready To Merge, BE, BUG!

#19 Wedding default image
  app/.flake8
  app/core/models.py
Labels: Author Needs Review, Author Thinks Ready To Merge, BE, BUG!, Reviewer Thinks Ready To Merge

#20 Create test for POST photo api. Add code for post_photo_api in serial…
  app/wedding/serializers.py
  app/wedding/tests/test_photo_api.py
  app/wedding/urls.py
  app/wedding/views.py
Labels: BE, Reviewer Thinks Ready To Merge

#21 Deploy
  .gitignore
  Dockerfile
  Dockerfile.prod
  app/app/settings.py
  app/entrypoint.prod.sh
  app/entrypoint.sh
  config/.env.dev
  config/.env.prod
  config/.env.prod.db
  docker-compose.prod.yml
  docker-compose.yml
  heroku.yml
  requirements.txt
Labels: Author Adds Line Comments, Author Needs Review, BE

#24 Get wedding guests api
  app/core/models.py
  app/wedding/tests/test_guest_api.py
  app/wedding/tests/test_photo_api.py
  app/wedding/urls.py
  app/wedding/views.py
Labels: Author Needs Review, BE

#26 Get wedding guests api
  app/core/migrations/0006_auto_20210112_0106.py
  app/core/models.py
  app/core/tests/test_models.py
  app/wedding/serializers.py
  app/wedding/tests/test_guest_api.py
  app/wedding/tests/test_photo_api.py
Labels: Author Thinks Ready To Merge, BE, Peer Coded

#27 Photo wedding
  app/core/migrations/0001_initial.py
  app/core/migrations/0002_auto_20210112_0300.py
  app/core/migrations/0002_guest.py
  app/core/migrations/0003_auto_20210105_2142.py
  app/core/migrations/0004_photo_photoguest.py
  app/core/migrations/0005_weddingguest.py
  app/core/migrations/0006_auto_20210112_0106.py
  app/core/models.py
  app/core/tests/test_models.py
  app/wedding/serializers.py
  app/wedding/tests/test_photo_api.py
  app/wedding/urls.py
  app/wedding/views.py
Labels: Author Needs Review, BE, Peer Coded, Priority #1, Reviewer Thinks Ready To Merge

#28 Tests format
  app/wedding/tests/test_guest_api.py
  app/wedding/tests/test_photo_api.py
  app/wedding/tests/test_wedding_api.py
Labels: Author Thinks Ready To Merge, BE, Reviewer Thinks Ready To Merge

#30 finish functionality for deleting a guest from the database with appr…
  app/wedding/tests/test_guest_api.py
  app/wedding/urls.py
  app/wedding/views.py
Labels: Author Needs Review, BE, Reviewer Thinks Ready To Merge

#40 Heroku deploy
  Dockerfile.prod
  app/app/settings.py
  heroku.yml
  requirements.txt
Labels: BE

#41 Add frontend app url to cors allowed origins
  app/app/settings.py
Labels: BE, BUG!
